make storage path configurable based on data_id or canonical link
World-Meteorological-Organization/pywis-pubsub pull request #31
Opened 2023-08-22 11:31 UTC by tomkralidis

When downloading data, the filepath is now configurable based on either `properties.data_id` (default) or the canonical link.  As well, `storage.options.path` is renamed to `storage.options.basedir`.

cc @mgiannoni

2023-08-23 09:51 UTC, maaikelimper requested changes
How about we use as default the topic+filename-from-url to save the file, and optionally 'link' or 'data_id' can be used as filename :
```
if filepath == 'link':
    # fetch canonical link and use local path, stripping slashes
    link = get_canonical_link(msg_dict['links'])
    filename = link['href'].split('/', 3)[-1].strip('/')
elif filepath == 'data_id':
    filename = msg_dict['properties']['data_id']
else:
    link = get_canonical_link(msg_dict['links'])
    filename = msg.topic+'/'+link['href'].split('/')[-1]
```

2023-08-23 12:52 UTC, mgiannoni commented
The 'canonical' form was interesting, it preserved the bucket timestamp
path - useful for aging the collection.

But I've noticed a few things:
1) What's with the "/wis/" part?   Shouldn't that be "/wis2/" ?  I'm still
searching for where this part of the path is constructed.
2) Somehow I've got "//data/" in there and that kind of mistake is going to
interfere with *split('/', 3) *

"href": "
http://wis2-networ-lb-cc22817f7ac75dec.elb.us-east-1.amazonaws.com:8999//data/
*2023-08-23*
/wis/usa/noaa_nws/data/core/weather/surface-based-observations/synop/WIGOS_0-20000-0-72295_20230823T120000.bufr4"

What about simply adding the file name extension onto the 'data_id' ?

 "data_id": "wis2/usa/noaa_nws/data/core/weather/surface-based-observations/synop/WIGOS_0-20000-0-72295_20230823T120000"
+ *".bufr4"*
 msg_dict['properties']['data_id'] +* link['href'].split('.')[-1]*

Marc Giannoni
Unix System Engineer, Guidehouse
Phone: 301.427.9478
Cell: 301.915.5266


On Wed, Aug 23, 2023 at 5:51 AM Maaike ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> How about we use as default the topic+filename-from-url to save the file,
> and optionally 'link' or 'data_id' can be used as filename :
>
> if filepath == 'link':
>     # fetch canonical link and use local path, stripping slashes
>     link = get_canonical_link(msg_dict['links'])
>     filename = link['href'].split('/', 3)[-1].strip('/')
> elif filepath == 'data_id':
>     filename = msg_dict['properties']['data_id']
> else:
>     link = get_canonical_link(msg_dict['links'])
>     filename = msg.topic+'/'+link['href'].split('/')[-1]
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/wmo-im/pywis-pubsub/pull/31#pullrequestreview-1591209533>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADYWE7TXD562ROVDEN47JJDXWXHCTANCNFSM6AAAAAA3ZYRFOQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-23 12:56 UTC, tomkralidis commented
We could add the file extension to the data_id (calling the option "combined").  What would happen if the canonical link does not have a file extension?  Should we consider the link's MIME type (`link.type`) if available, else return as data_id?

2023-08-23 13:15 UTC, mgiannoni commented
Good catch Tom, and looking into this from the Global Cache, I found an
example!  Also an edge-case where the "href" path has been stripped of the
'topic'.

"data_id":
"wis2/xxf/eumetsat/data/core/weather/space-based-observations/satellite4nowcasting/Meteosat-10/ImageL1-5/H-000-MSG3__-MSG3________-IR_134___-000004___-202308231300-C_"
,
"href": "
https://opendata.dwd.de/test/wis2/cache/xxf/eumetsat/H-000-MSG3__-MSG3________-IR_134___-000004___-202308231300-C_
",

I suppose having the topic in the file path is not entirely necessary, but
I happen to prefer this built-in feature of the "data_id".   This way all
the files for the Wis2 the system can be placed into a single file system
or S3 bucket without any ambiguity.


Marc Giannoni
Unix System Engineer, Guidehouse
Phone: 301.427.9478
Cell: 301.915.5266


On Wed, Aug 23, 2023 at 8:57 AM Tom Kralidis ***@***.***>
wrote:

> We could add the file extension to the data_id (calling the option
> "combined"). What would happen if the canonical link does not have a file
> extension? Should we consider the link's MIME type (link.type) if
> available, else return as data_id?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/wmo-im/pywis-pubsub/pull/31#issuecomment-1689915495>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADYWE7T2SHUAFYPDSWLAGBTXWX4ZNANCNFSM6AAAAAA3ZYRFOQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-23 14:40 UTC, maaikelimper commented
I don't think the data_id neccessarily has the built-in feature of the topic,  I understood it is up to the publisher to define the data_id. 
I think if we want to be sure to get the topic the data was published on in the filepath, pywis-pubsub needs to prepend msg.topic to the filename ?

2023-08-27 21:15 UTC, tomkralidis commented
PR updated as per https://github.com/wmo-im/pywis-pubsub/issues/27#issuecomment-1690265225

2023-08-28 11:15 UTC, maaikelimper approved these changes

2023-08-28 11:28 UTC, merged