add option to publish the data inline as base64
World-Meteorological-Organization/pywis-pubsub pull request #48
Opened 2023-11-14 00:06 UTC by tomkralidis

2023-11-14 14:07 UTC, maaikelimper commented
Why is the default for inline false instead of true ? And why do we have an option to set this to false at all ?

2023-11-14 14:12 UTC, tomkralidis commented
Different than wis2box (who emits by default). The option is there for users want to emit the data explicitly (in the generic tool context).

If this is overhead and pywis-pubsub should just publish inline (if data is less than 4096 bytes per the WNM specification), then I can update the PR. Preference?

2023-11-14 14:12 UTC, maaikelimper requested changes

2023-11-14 14:12 UTC, maaikelimper commented on pywis_pubsub/publish.py
> +    :inline: `bool` of whether to publish the data inline as base64
This comment is slightly misleading, the data will only be published inline if this boolean is true -and- the data-size is less than 4096 bytes

2023-12-04 08:05 UTC, maaikelimper approved these changes

2023-12-04 15:17 UTC, merged