Customize MQTT Client ID Using A Parameter
World-Meteorological-Organization/pywis-pubsub pull request #60
Opened 2024-06-07 16:57 UTC by mgiannoni

Use the "client_id" parameter to set the MQTT Client ID.

+            try:
+                self.client_id = f"{options['client_id']}-{random.randint(0, 1000)}"
+            except:
+                self.client_id = f'pywis-pubsub-{random.randint(0, 1000)}'

2024-06-09 15:36 UTC, tomkralidis requested changes

2024-06-09 15:36 UTC, tomkralidis commented on pywis_pubsub/mqtt.py
> +            try:
Suggest:

```python
        client_id_prefix = options.get('client_id', 'pywis-pubsub')
        self.client_id = f'{client_id_prefix}-{random.randint(0, 1000)}'
```

2024-06-09 15:36 UTC, tomkralidis commented on pywis_pubsub/subscribe.py
> +    default_client_id = f'pywis-pubsub'
Suggest:

```python
        client_id_prefix = config.get('client_id', 'pywis-pubsub')
        client_id = f'{client_id_prefix}-{random.randint(0, 1000)}'
```

2024-06-10 13:30 UTC, mgiannoni commented on pywis_pubsub/mqtt.py
> +            try:
Better, yes.  Thanks Tom

2024-06-10 13:30 UTC, mgiannoni commented on pywis_pubsub/subscribe.py
> +    default_client_id = f'pywis-pubsub'
Better again, thanks Tom.

2024-06-28 00:26 UTC, mgiannoni commented
Tom:
Made the suggested changes discussed June 27th.
Ready for your review.

Thanks
Marc G

2024-06-28 10:10 UTC, tomkralidis approved these changes

2024-06-28 10:10 UTC, merged

2024-06-28 10:10 UTC, tomkralidis commented
Thanks @mgiannoni!